# MIT License
#
# Copyright (c) 2026 VinRobotics
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vlm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvlm.proto\x12\x08vlm_chat\"\x82\x01\n\x05Image\x12*\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x18.vlm_chat.Image.Encoding\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\" \n\x08\x45ncoding\x12\x08\n\x04JPEG\x10\x00\x12\n\n\x06RGB_U8\x10\x01\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"e\n\x0eSamplingParams\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\r\n\x05top_p\x18\x02 \x01(\x02\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x0c\n\x04seed\x18\x05 \x01(\x04\"\xa7\x01\n\x0b\x43hatRequest\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.vlm_chat.ChatMessage\x12\x1f\n\x06images\x18\x02 \x03(\x0b\x32\x0f.vlm_chat.Image\x12*\n\x08sampling\x18\x03 \x01(\x0b\x32\x18.vlm_chat.SamplingParams\x12\x0e\n\x06stream\x18\x04 \x01(\x08\x12\x12\n\nrequest_id\x18\x05 \x01(\x04\"\xd9\x01\n\x0c\x43hatResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\x12\x15\n\rprompt_tokens\x18\x04 \x01(\r\x12\x19\n\x11\x63ompletion_tokens\x18\x05 \x01(\r\x12\x18\n\x10latency_ms_total\x18\x06 \x01(\x02\x12\x1a\n\x12latency_ms_prefill\x18\x07 \x01(\x02\x12\x19\n\x11latency_ms_decode\x18\x08 \x01(\x02\x12\r\n\x05\x65rror\x18\t \x01(\t\"4\n\x0f\x43hatStreamDelta\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\t\"l\n\rStreamMessage\x12*\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\x19.vlm_chat.ChatStreamDeltaH\x00\x12\'\n\x05\x66inal\x18\x02 \x01(\x0b\x32\x16.vlm_chat.ChatResponseH\x00\x42\x06\n\x04kindb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vlm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=24
  _IMAGE._serialized_end=154
  _IMAGE_ENCODING._serialized_start=122
  _IMAGE_ENCODING._serialized_end=154
  _CHATMESSAGE._serialized_start=156
  _CHATMESSAGE._serialized_end=200
  _SAMPLINGPARAMS._serialized_start=202
  _SAMPLINGPARAMS._serialized_end=303
  _CHATREQUEST._serialized_start=306
  _CHATREQUEST._serialized_end=473
  _CHATRESPONSE._serialized_start=476
  _CHATRESPONSE._serialized_end=693
  _CHATSTREAMDELTA._serialized_start=695
  _CHATSTREAMDELTA._serialized_end=747
  _STREAMMESSAGE._serialized_start=749
  _STREAMMESSAGE._serialized_end=857
# @@protoc_insertion_point(module_scope)
